"""Initial migration

Revision ID: 81c35edd13b8
Revises: 
Create Date: 2026-05-17 00:25:35.351995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c35edd13b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_holdings', 'holding_percentage',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Numeric(precision=10, scale=4),
               nullable=False)
    op.create_index(op.f('ix_fund_holdings_disclosure_date'), 'fund_holdings', ['disclosure_date'], unique=False)
    op.create_index(op.f('ix_fund_holdings_scheme_code'), 'fund_holdings', ['scheme_code'], unique=False)
    op.create_index(op.f('ix_fund_holdings_stock_isin'), 'fund_holdings', ['stock_isin'], unique=False)
    op.create_index(op.f('ix_funds_amc_name'), 'funds', ['amc_name'], unique=False)
    op.create_index(op.f('ix_funds_category'), 'funds', ['category'], unique=False)
    op.create_index(op.f('ix_funds_scheme_code'), 'funds', ['scheme_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funds_scheme_code'), table_name='funds')
    op.drop_index(op.f('ix_funds_category'), table_name='funds')
    op.drop_index(op.f('ix_funds_amc_name'), table_name='funds')
    op.drop_index(op.f('ix_fund_holdings_stock_isin'), table_name='fund_holdings')
    op.drop_index(op.f('ix_fund_holdings_scheme_code'), table_name='fund_holdings')
    op.drop_index(op.f('ix_fund_holdings_disclosure_date'), table_name='fund_holdings')
    op.alter_column('fund_holdings', 'holding_percentage',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=6, scale=3),
               nullable=True)
    # ### end Alembic commands ###
